### ISSUE TITLE
Prevent multiple Tabl_ dialogs

### ISSUE THREAD

**Issue by tmwarchitecture** [tmwarchitecture/Tabl_#12]

**Comment by visualizor** [comment]
In winforms, which is the library I'm using to re-write the UI, it can be an object owned by the command (when one types "Tabl_"). I can attach a `OnClosing` handler to the `Form.FormClosing` event, and intercept the `Dispose()` call, so once a `Form` is instantiated it's always there. Then `Show()` or `Hide()` as one pleases. Not sure if `Eto.Forms.Form` has similar methods and events...you can look

**Comment by tmwarchitecture** [comment]
Issue resolved in version 2.0 rewrite.
