### ISSUE TITLE
Icons not resizing on high resolution monitors

### ISSUE THREAD

**Issue by tmwarchitecture** [tmwarchitecture/Tabl_#34]
Seems it can be solved by supplying icons of 3 different sizes. 
16x16, 32x32, and 64x64

Another plugin mentioning using different icon sizes.
https://discourse.mcneel.com/t/eto-window-icon-property-raises-handle-is-invalid-exception-in-rhino-6-sr26/103506

**Comment by visualizor** [comment]
@tmwarchitecture can you try again on your wife's pc? I've changed a scaling mode to DPI-based on the pop up forms. I wonder how it looks or it did anything at all. regardless of the icon issue.

**Comment by visualizor** [comment]
unfortunately winforms buttons don't use .ico files in its scalable way. the only option is to stretch the raster image on the button. big, but blurry.

**Comment by tmwarchitecture** [comment]
Tested it, the icons still appear small, BUT the settings dialog now properly scales! There is some clipping occurring on some of the labels, but that's the only issue.

![image](https://user-images.githubusercontent.com/17794088/107636867-e5881f00-6c32-11eb-871f-a4d4ef5577cb.png)

**Comment by visualizor** [comment]
trying 2x images to begin with

**Comment by tmwarchitecture** [comment]
No visible difference here. Becoming a wontfix issue. It is still totally usable, just tiny buttons.

Additionally, there seems to be an additional button that is orange at the end (I'm guessing for debugging).

Small improvement on the settings width haha.
![image](https://user-images.githubusercontent.com/17794088/107767952-58f56380-6cfb-11eb-89d1-a8460bf8660e.png)
