### ISSUE TITLE
Readability enhancement - Columns containing numbers

### ISSUE THREAD

**Issue by tmwarchitecture** [tmwarchitecture/Tabl_#35]
**Add trailing zero to decimal numbers**
Goes with the next enhancement to make decimal points align for readability.
--3.45
--3.41
---3.4

vs.
--3.45
--3.41
--3.40

**Numbers should be right-justify**
More difficult to read numbers when center justify.
335434.23
--123.12
---2.14

vs.
Right justify
335434.23
----123.12
-------2.14

**Comment by tmwarchitecture** [comment]
Right justify seems to be working! I'm still seeing the trailing zero issue on last nights build.

**Comment by visualizor** [comment]
![image](https://user-images.githubusercontent.com/25107288/107722558-2f155000-6cad-11eb-9bed-78c1b833833e.png)
