### ISSUE TITLE
multi-thread crash

### ISSUE THREAD

**Issue by visualizor** [tmwarchitecture/Tabl_#40]
be sure to duplicate subject geometry for thread safety

**Comment by visualizor** [comment]
stability issues
seems to work fine with debugger attached but not in standalone

**Comment by visualizor** [comment]
@tmwarchitecture 
![image](https://user-images.githubusercontent.com/25107288/107889657-2fe2f780-6ee2-11eb-9cfc-b8af5a8f38ea.png)
Please test latest build, which is compiled under debug mode. 

On my machine, when compiled under a "release" mode, multi-thread crashes often (seems to be memory access errors).
When compiled under "debug" mode, however, I have not crashed once. Please confirm. I can't tell if I just got lucky with the debug compilation.

**Comment by tmwarchitecture** [comment]
I loaded 10,000 curves, 10,000 surfaces, and 10,000 closed polysurfaces and displayed the length, area, and volume. 
It took 12 seconds with threading on, and 28 seconds with it off. I was never able to make it crash (Which I guess is good news and bad news).

**Comment by visualizor** [comment]
Thanks! I'm not gonna dwell on it then. This release mode supposedly optimizes the code but one I've noticed no difference so far and two I don't even know in what ways does it "optimize" the code.
Gosh, 30,000 objects will crash Rhino on their own....
